replicaCount: 2

image:
  repository: your-account-id.dkr.ecr.us-east-1.amazonaws.com/myapp-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: alb
  hosts:
  - host: myapp.example.com
    paths:
    - path: /
      pathType: Prefix
